Algoritmo "aula_3.1"





Var
n1, n2, soma, divisao, multi, sub: real

Inicio
Escreva ("Digite o primeiro número: ")
Leia (n1)
Escreva ("Digite o segundo número: ")
Leia (n2)
soma:= n1+n2
divisao:= n1/n2
multi:= n1*n2
sub:= n1-n2
limpatela
Escreval ("A soma é" , soma)
Escreval ("A divisão é" , divisao)
Escreval ("A multiplicação é" , multi)
Escreval ("A subtração é" , sub)

Fimalgoritmo