Algoritmo "estrutura_condicional"



Var

n1, n2, n3, media: real

Inicio

escreva ("Informe a primeira nota do aluno: ")
leia (n1)
escreva ("Informe a segunda nota do aluno: ")
leia (n2)
escreva ("Informe a terceira nota do aluno: ")
leia (n3)
media:= (n1+n2+n3)/3
se media >= 7 entao
escreval ("Aprovado com média: ", media:2:1)
senao
escreval ("Reprovado com média: ", media:2:1)
fimse

Fimalgoritmo