Algoritmo "estrutura_condicional"



Var

n1, n2, n3: real

Inicio

escreva ("Digite o primeiro número: ")
leia (n1)
escreva ("Digite o segundo número: ")
leia (n2)
escreva ("Digite o terceiro número: ")
leia (n3)
se (n1<n2) e (n1<n3) entao
escreval ("O menor número é ", n1)
senao
se (n2<n3) entao
escreval ("O menor número é ", n2)
senao
escreval ("O menor número é ", n3)
fimse
fimse

Fimalgoritmo