Algoritmo "switch_case.2"



Var

color: caractere

Inicio

escreval ("Informe a cor: ")
leia (color)
escolha color
        caso "VERDE"
             escreva ("Preço: R$ 10.00")
        caso "AZUL"
             escreva ("Preço: R$ 20.00")
        caso "AMARELO"
             escreva ("Preço: R$ 30.00")
        caso "VERMELHO"
             escreva ("Preço: R$ 40.00")
        outrocaso
             escreva ("Cor inválida!!")
fimescolha

Fimalgoritmo